{
 "title": "mydashboard",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "/health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(webapp_path_counter{job=\"discover-webapp\",path=\"/health\"})"
    }
   ]
  },
  {
   "title": "/ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(webapp_path_counter{job=\"discover-webapp\",path=\"/ready\"})"
    }
   ]
  },
  {
   "title": "/user",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(webapp_path_counter{job=\"discover-webapp\",path=\"/user\"})"
    }
   ]
  },
  {
   "title": "/watch",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(webapp_path_counter{job=\"discover-webapp\",path=\"/watch\"})"
    }
   ]
  },
  {
   "title": "Webapp Database Health Status Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webapp_request_timed_calls{job=\"discover-webapp\",operation=\"database_health_status\",quantile=\"0.01\"}"
    }
   ]
  },
  {
   "title": "Webapp Database Ready Status Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webapp_request_timed_calls{job=\"discover-webapp\",operation=\"database_ready_status\",quantile=\"0.01\"}"
    }
   ]
  },
  {
   "title": "Poller Kakfa Message Counter Publish/Consume",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poller_kafka_message_counter{instance=\"poller-poll:3001\", topic=\"weather\",type=\"publish\"}"
    },
    {
     "expr": "poller_kafka_message_counter{instance=\"poller-poll:3001\", topic=\"watch\",type=\"consume\"}"
    }
   ]
  },
  {
   "title": "Create Watch Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webapp_request_timed_calls{job=\"discover-webapp\",operation=\"create_watch\",quantile=\"0.01\",statusCode=\"200\"}"
    }
   ]
  },
  {
   "title": "Create User Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webapp_request_timed_calls{instance=\"100.96.5.7:3000\",job=\"discover-webapp\",operation=\"create_user\",quantile=\"0.01\",statusCode=\"200\"}"
    }
   ]
  },
  {
   "title": "Notifier Kafka Message Consume",
   "type": "graph",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "notifier_kafka_message_counter" }
   ]
  },
  {
   "title": "Webapp Kafka Health Status Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webapp_request_timed_calls{job=\"discover-webapp\",operation=\"kafka_health_status\",quantile=\"0.01\"}"
    }
   ]
  },
  {
   "title": "Webapp Kafka Ready Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webapp_request_timed_calls{job=\"discover-webapp\",operation=\"kafka_health_status\",quantile=\"0.999\"}"
    }
   ]
  },
  {
   "title": "Kafka Brokers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_brokers{instance=\"kafka-exporter:9308\",job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Poller Kafka Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "poller_request_timed_calls{instance=\"poller-poll:3001\",job=\"prometheus\",quantile=\"0.01\",service=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Kafka Topic Partitions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partitions{instance=\"kafka-exporter:9308\",job=\"prometheus\",topic=\"weather\"}"
    },
    {
     "expr": "kafka_topic_partitions{instance=\"kafka-exporter:9308\",job=\"prometheus\",topic=\"watch\"}"
    }
   ]
  }
 ]
}